name: Deploy Postgres Infra

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: |
          cd db-infra
          terraform init

    - name: Terraform Plan
      run: |
          cd db-infra
          terraform plan

    - name: Terraform Apply
      run: |
          cd db-infra
          terraform apply -auto-approve

    - name: Test Database Connection
      run: |
        echo "Testing connection to PostgreSQL..."
        psql "host=${{ secrets.POSTGRES_HOST }} user=${{ secrets.POSTGRES_USER }} password=${{ secrets.POSTGRES_PASSWORD }} dbname=${{ secrets.POSTGRES_DB }}" -c '\l'
